name: SAMS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8 (PEP 8 Check)
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings. 
        # The project currenty has issues, so we start by showing errors.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Custom: exit-zero to not block PRs immediately while you are refactoring
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Basic Smoke Test (Verify modules load)
      run: |
        # Ensure the core system can at least be imported without crashing
        python -c "import core; import ui; import viz; print('✅ Modules loaded successfully')"
